name: build-ubuntu
on: [ push ]
jobs:
  build-cmake:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup node
        shell: bash
        run: |
          curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
          architecture: x64
      - name: install dependencies
        shell: bash
        run: |
          pip install -r scripts/requirements.txt
          python -m scripts sync-deps
      - name: configure cmake
        shell: bash
        run: |
          python -m scripts configure cmake Release -G "Unix Makefiles"
      - name: build!
        shell: bash
        run: |
          make -C ${{ github.workspace }}/build -j 8
      - name: package
        id: package
        uses: yodasoda1219/create-package@v2.1
        with:
          config: artifacts/unix.json
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: ${{ steps.package.outputs.path }}