name: build-windows
on: [ push ]
jobs:
  build-cmake:
    runs-on: windows-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
          architecture: x64
      - name: install dependencies
        shell: cmd
        run: |
          pip install -r scripts\requirements.txt
          python -m scripts sync-deps
      - name: configure cmake
        shell: cmd
        run: |
          python -m scripts configure cmake Release -G "Visual Studio 16 2019"
      - name: build!
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" build\libglplayground.sln -p:Configuration=Release -m