name: build-ubuntu
on: [ push ]
jobs:
  build-cmake:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
      - name: setup node
        shell: bash
        run: |
          curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - name: configure cmake
        shell: bash
        run: |
          cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release
      - name: build!
        shell: bash
        run: |
          make -C ${{ github.workspace }}/build -j 8
      - name: package
        id: package
        uses: yodasoda1219/create-package@v2.1
        with:
          config: artifacts/unix.json
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: ${{ steps.package.outputs.path }}