name: build-macosx
on: [ push ]
jobs:
  build-cmake:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: configure cmake
        shell: bash
        run: |
          cmake ${{ github.workspace }} -B ${{ github.workspace }}/build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
      - name: build!
        shell: bash
        run: |
          make -C ${{ github.workspace }}/build -j 8
      - name: package
        id: package
        uses: yodasoda1219/create-package@v2.1
        with:
          config: artifacts/unix.json
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: macosx-build
          path: ${{ steps.package.outputs.path }}